// swift-tools-version: 5.6
// WARNING: This file is automatically generated. Do not edit it by hand because the contents will be replaced.

import PackageDescription
#if canImport(AppleProductTypes)
import AppleProductTypes
#endif

#if canImport(AppleProductTypes)
let package = Package(
    name: "EcoTide",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "EcoTide",
            targets: ["AppModule"],
            bundleIdentifier: "com.doeon.EcoTide",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .earth),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .motion(purposeString: "EcoTide uses device motion to manipulate standard gravity in the physics simulation.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
#else
let package = Package(
    name: "EcoTide",
    platforms: [
        .macOS("12.0")
    ],
    products: [
        .executable(
            name: "EcoTide",
            targets: ["AppModule"]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
#endif
