// swift-tools-version: 5.6
// WARNING: This file is automatically generated. Do not edit it by hand because the contents will be replaced.

import PackageDescription
#if canImport(AppleProductTypes)
import AppleProductTypes
#endif

let package: Package = {
#if canImport(AppleProductTypes)
    return Package(
        name: "EcoTide",
        platforms: [
            .iOS("16.0")
        ],
        products: [
            .iOSApplication(
                name: "EcoTide",
                targets: ["AppModule"],
                bundleIdentifier: "com.doeon.EcoTide",
                teamIdentifier: "",
                displayVersion: "1.0",
                bundleVersion: "1",
                appIcon: .placeholder(icon: .earth),
                accentColor: .presetColor(.blue),
                supportedDeviceFamilies: [
                    .pad,
                    .phone
                ],
                supportedInterfaceOrientations: [
                    .portrait,
                    .landscapeRight,
                    .landscapeLeft,
                    .portraitUpsideDown(.when(deviceFamilies: [.pad]))
                ],
                capabilities: [
                    .motion(purposeString: "EcoTide uses device motion to manipulate standard gravity in the physics simulation.")
                ]
            )
        ],
        targets: [
            .target(
                name: "EcoTideShared",
                path: "Shared"
            ),
            .executableTarget(
                name: "AppModule",
                dependencies: ["EcoTideShared"],
                path: ".",
                exclude: ["Shared", "spm-cli", "Tests"]
            )
        ]
    )
#else
    return Package(
        name: "EcoTide",
        products: [
            .executable(
                name: "EcoTideCLI",
                targets: ["AppModule"]
            )
        ],
        targets: [
            .target(
                name: "EcoTideShared",
                path: "Shared"
            ),
            .executableTarget(
                name: "AppModule",
                dependencies: ["EcoTideShared"],
                path: "spm-cli"
            )
        ]
    )
#endif
}()
